################################################################################

# Messages for status and commands. We use plain text so we can read status and send commands via a terminal.

ALL = 'ALL'
AUTO = 'AUTO'
ACTIVE = 'ACTIVE'

BROADCAST = 'BROADCAST'
BUTTON_STOP = 'BUTTON STOP'
BUTTON_OPEN = 'BUTTON OPEN'
BUTTON_PED = 'BUTTON PED'
BUTTON_OPEN_PRESSED = 'BUTTON OPEN PRESSED' 
BUTTON_OPEN_RELEASED = 'BUTTON OPEN RELEASED'
BUTTON_STOP_PRESSED = 'BUTTON STOP PRESSED' 
BUTTON_STOP_RELEASED = 'BUTTON STOP RELEASED'
BUTTON_PED_PRESSED = 'BUTTON PED PRESSED'
BUTTON_PED_RELEASED = 'BUTTON PED RELEASED'

CLOSE = 'CLOSE'
CLOSED = 'CLOSED'
CLOSING = 'CLOSING'
CLOSING_HALTED = 'CLOSING_HALTED'
CLOSED_SWITCH = 'CLOSED_SWITCH'
CRLF = '\r\n'

DAY = 'DAY'
DRIVE = 'DRIVE'

EXTERIOR_LIGHTS_ON = 'EXTERIOR LIGHTS ON'
EXTERIOR_LIGHTS_OFF = 'EXTERIOR LIGHTS OFF'

FRONT = 'FRONT'
FLASH1 = 'FLASH1'
FLASH2 = 'FLASH2'
FAILED = 'FAILED'

GATES = 'GATES'
GATES_ARE_MOVING = 'GATES ARE MOVING'
GATES_ARE_STOPPED = 'GATES ARE STOPPED'
GATES_OPEN = 'GATES OPEN' #1
GATES_OPENING = 'GATES OPENING' #1
GATES_CLOSED = 'GATES CLOSED' #1
GATES_CLOSING = 'GATES CLOSING' #1
GATES_HALTED = 'GATES HALTED' #1
GATES_RESTARTING = 'GATES RESTARTING' #1
GATES_BUSY = 'GATES BUSY' #1
GREEN = 'GREEN'

INACTIVE = 'INACTIVE'

LAST = 'LAST'
LEFT_GATE = 'LEFT_GATE'


MOVING = 'MOVING'

NIGHT = 'NIGHT'

ON = 'ON'
OFF = 'OFF'
OK = 'OK'
OFFLINE = 'OFFLINE'
ONLINE = 'ONLINE'
OPEN = 'OPEN'
OPENING = 'OPENING'
OPENING_HALTED = 'OPENING_HALTED'
OPEN_SWITCH = 'OPEN_SWITCH'
OUTPUT_START_IS_OFF = 'OUTPUT START IS OFF'
OUTPUT_START_IS_ON = 'OUTPUT START IS ON'
OUTPUT_STOP_IS_OFF = 'OUTPUT STOP IS OFF'
OUTPUT_STOP_IS_ON = 'OUTPUT STOP IS ON'
OUTPUT_PED_IS_OFF = 'OUTPUT PED IS OFF'
OUTPUT_PED_IS_ON = 'OUTPUT PED IS ON'
OUTPUT_GREEN_IS_OFF = 'OUTPUT GREEN IS OFF'
OUTPUT_GREEN_IS_ON = 'OUTPUT GREEN IS ON'
OUTPUT_RED_IS_OFF = 'OUTPUT RED IS OFF'
OUTPUT_RED_IS_ON = 'OUTPUT RED IS ON'
OUTPUT_DRIVE_IS_OFF = 'OUTPUT DRIVE IS OFF'
OUTPUT_DRIVE_IS_ON = 'OUTPUT DRIVE IS ON'
OUTPUT_FRONT_IS_OFF = 'OUTPUT FRONT IS OFF'
OUTPUT_FRONT_IS_ON = 'OUTPUT FRONT IS ON'
OUTPUT_SIGN_IS_OFF = 'OUTPUT SIGN IS OFF'
OUTPUT_SIGN_IS_ON = 'OUTPUT SIGN IS ON'


PED= 'PED'
PRESSED = 'PRESSED'

RED = 'RED'
RELEASED = 'RELEASED'
RIGHT_GATE = 'RIGHT_GATE'

STOPPED = 'STOPPED'
STATUS = 'STATUS'
START = 'START'
STOP = 'STOP'
SIGN = 'SIGN'
SET_DAY_MODE = 'SET DAY MODE'
SET_NIGHT_MODE = 'SET NIGHT MODE'

SPACE = ' '

SWITCH_LEFT_OPEN = 'SWITCH LEFT OPEN'
SWITCH_LEFT_CLOSED = 'SWITCH LEFT CLOSED'
SWITCH_RIGHT_OPEN = 'SWITCH RIGHT OPEN'
SWITCH_RIGHT_CLOSED = 'SWITCH RIGHT CLOSED'

SWITCH_LEFT_CLOSED_ACTIVE = 'SWITCH LEFT CLOSED ACTIVE' 
SWITCH_LEFT_CLOSED_INACTIVE = 'SWITCH LEFT CLOSED INACTIVE'
SWITCH_LEFT_OPEN_ACTIVE = 'SWITCH LEFT OPEN ACTIVE' 
SWITCH_LEFT_OPEN_INACTIVE = 'SWITCH LEFT OPEN INACTIVE'
SWITCH_RIGHT_CLOSED_ACTIVE = 'SWITCH RIGHT CLOSED ACTIVE'
SWITCH_RIGHT_CLOSED_INACTIVE = 'SWITCH RIGHT CLOSED INACTIVE' 
SWITCH_RIGHT_OPEN_ACTIVE = 'SWITCH RIGHT OPEN ACTIVE'
SWITCH_RIGHT_OPEN_INACTIVE = 'SWITCH RIGHT OPEN INACTIVE'

GATE_LEFT_CLOSING = 'GATE LEFT CLOSING' #1
GATE_LEFT_OPENING = 'GATE LEFT OPENING' #1
GATE_LEFT_FORCED = 'GATE LEFT FORCED' #1

GATE_RIGHT_CLOSING = 'GATE RIGHT CLOSING' #1
GATE_RIGHT_OPENING = 'GATE RIGHT OPENING' #1
GATE_RIGHT_FORCED = 'GATE RIGHT FORCED' #1

GATE_BUTTON_OPEN_PRESSED = 'GATE BUTTON OPEN PRESSED' #1
GATE_BUTTON_OPEN_RELEASED = 'GATE BUTTON OPEN RELEASED' #1
GATE_BUTTON_STOP_PRESSED = 'GATE BUTTON STOP PRESSED' #1
GATE_BUTTON_STOP_RELEASED = 'GATE BUTTON STOP RELEASED' #1
GATE_BUTTON_PED_PRESSED = 'GATE BUTTON PED PRESSED' #1
GATE_BUTTON_PED_RELEASED = 'GATE BUTTON PED RELEASED' #1

GATE_SWITCH_LEFT_CLOSED_ACTIVE = 'GATE SWITCH LEFT CLOSED ACTIVE' #1
GATE_SWITCH_LEFT_CLOSED_INACTIVE = 'GATE SWITCH LEFT CLOSED INACTIVE' #1
GATE_SWITCH_LEFT_OPEN_ACTIVE = 'GATE SWITCH LEFT OPEN ACTIVE'  #1
GATE_SWITCH_LEFT_OPEN_INACTIVE = 'GATE SWITCH LEFT OPEN INACTIVE' #1
GATE_SWITCH_RIGHT_CLOSED_ACTIVE = 'GATE SWITCH RIGHT CLOSED ACTIVE' #1
GATE_SWITCH_RIGHT_CLOSED_INACTIVE = 'GATE SWITCH RIGHT CLOSED INACTIVE'  #1
GATE_SWITCH_RIGHT_OPEN_ACTIVE = 'GATE SWITCH RIGHT OPEN ACTIVE' #1
GATE_SWITCH_RIGHT_OPEN_INACTIVE = 'GATE SWITCH RIGHT OPEN INACTIVE' #1


# Identifiers for the system and the various controllers.
SYSTEM_ID = 'FIDDLERSGREEN'
GATE_ID = 'GATECONTROLLER'
BU_GATE_ID = 'BACKUPGATECONTROLLER'
GSM_ID = 'GSMCONTROLLER'
BU_GSM_ID = 'BACKUPGSMCONTROLLER'
LIGHTS_ID = 'LIGHTSCONTROLLER'
# Keep a table of all known controllers.
OURCONTROLLERS = (GATE_ID, BU_GATE_ID, GSM_ID, BU_GSM_ID, LIGHTS_ID)


################################################################################
